/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.cloudbus.cloudsim;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Scrollbar;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.List;
import java.util.Random;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;
import org.cloudbus.cloudsim.Datacenter;
import org.cloudbus.cloudsim.DatacenterBroker1;
import org.cloudbus.cloudsim.DatacenterCharacteristics;
import org.cloudbus.cloudsim.core.CloudSimTags;

/**
 *
 * @author Nadhiya
 */
public class Load extends javax.swing.JFrame {
public static JTable tvl2;
public static DefaultTableModel dtm2;
public static JTable tvl3;
public static DefaultTableModel dtm3;
public static int arrcapacity[]=new int[1000];
public static int available[]=new int[1000];
public static int a[]=new int[1000];
public static int b[]=new int[1000];

static List vmlist;
static List cloudletList;
    static Random rand=new Random();
    int r=rand.nextInt(20)+25;
   public static int s;


    /**
     * Creates new form Load
     */
    public Load() {
        initComponents();
         getContentPane().setBackground(Color.pink);
      
         tvl2=new JTable();
         
           dtm2=new DefaultTableModel(0,0);
          tvl2.setBackground(Color.pink);
          tvl2.setBounds(350,100,330,600);
           
           String header2[]=new String[]{"CloudLet Allocation"};
           dtm2.setColumnIdentifiers(header2);
           tvl2.setDragEnabled(true);
           tvl2.setModel(dtm2);
     
           this.add(tvl2);
           
            
           tvl3=new JTable();
           
           Dimension d=new Dimension(30,40);
           tvl3.setPreferredScrollableViewportSize(d);
           tvl3.setFillsViewportHeight(true);
           dtm3=new DefaultTableModel(0,0);
           tvl3.setBackground(Color.pink);
           tvl3.setBounds(50,230,100,80);
          
           
           String header[]=new String[]{"VM space"};
           tvl3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
           dtm3.addColumn(" VM SPACE");
          
           //JScrollPane js=new JScrollPane(tvl3);
           
           /*js.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS); 
           js.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS); 
           js.setBounds(50,230,100,60);
           add(js);
           js.setVisible(true);
           getContentPane().add(js);*/
          
         
           tvl3.setModel(dtm3);
     
           this.add(tvl3);
           
           
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Allocation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("No.of Cloudlets :");

        jButton2.setText("Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Available space in Vm");

        jLabel3.setText("Utilizing the Available Space");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 410, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jLabel1.setText(jLabel1.getText()+r+"  ");
        String l=" ";
        cloudletList=Case.createCloudlet(0,r,0);
        for(int i=0;i<r;i++)
        {
            a[i]=Case.jobsize[i];
        }
        
       for(int i=0;i<=4;i++)
       {   
           dtm3.addRow(new Object[]{"VM: "+i+" "+Scenario.available[i]+" "});
           b[i]= Scenario.available[i];
           
       }
        s=4;
       for(int i=0;i<r;i++){
           int check=0;
         
       for(int j=0;j<=s+1;j++)
       {
       if(check!=1&&a[i]<=b[j])
       { 
       b[j]=b[j]-a[i];
       l="cloudlet  "+ i+"  allocated to Vm "+ j+" load : "+a[i]+"avail "+b[j]; 
      
       dtm2.addRow(new Object[]{l});
       check=1;
       }
         
       }
            
           if(check!=1)
           {
           
          s=s+1;
          b[s]=12500-a[i];
            l="cloudlet  "+ i+"  allocated to new  Vm "+s+" load  "+a[i]+ "avail"+b[s];
            dtm2.addRow(new Object[]{l});
            
           } 
          
          
       }
       
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        f3 f=new f3();
        f.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
